### ISSUE TITLE
what device do you used in exps?

### ISSUE THREAD

**Issue by fuxuelinwudi** [zhouchenlin2096/Spikingformer-CML#2]
I need your device name

**Comment by zhouchenlin2096** [comment]
A 100

**Comment by fuxuelinwudi** [comment]
I use A100 to do exps on paper of  Spikformer, but the results didn't like what you described in paper, such as  cifar10, my top1 score is 94.75, but yours is 95.19; my envs has been modified as same as you described in README, so I'm wondering that what cause my score being different (lower) with yours?

**Comment by zhouchenlin2096** [comment]
95.19???Spikformer??? Spikformer is not my work. I just copied the results of Spikformer from《 Spikformer: When spiking neural network meets transformer. In The Eleventh International Conference on Learning Representations, 2023.》https://openreview.net/pdf?id=frE4fUwz_h

I mainly created the model of Spikingformer and Spikingformer-CML. If you have any questions about using both Spikingformer and Spikingformer-CML, please contact me.

**Comment by fuxuelinwudi** [comment]
Ok, fine. Thanks a lot, bro.

**Comment by fuxuelinwudi** [comment]
兄弟，torch好像没有1.14.0的版本，官网最高就1.13的，然后直接2.0了，你是不是写错了？

**Comment by zhouchenlin2096** [comment]
感谢提醒！！！
1.14那个以前有，现在没了。
用这个环境也可以的：timm==0.6.12; cupy==11.4.0; torch==1.12.1; spikingjelly==0.0.0.0.12; pyyaml; 
我已经在git上更正了。

**Comment by touristourist** [comment]
> A 100

How many GPU hours did you spend on training Spikingformer-CML on Imagenet-1k?

**Comment by fuxuelinwudi** [comment]
I haven't did exp on Imagentet-1K yet, sorry.&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月24日(星期二) 下午3:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhouchenlin2096/Spikingformer-CML] what device do you used in exps? (Issue #2)





  
A 100
  
How many GPU hours did you spend on training Spikingformer-CML on Imagenet-1k?

**Comment by zhouchenlin2096** [comment]
> > A 100
> 
> How many GPU hours did you spend on training Spikingformer-CML on Imagenet-1k?

About 7 X 24 hours on the 384 model, and about 15 X 24 on the 768 model.
