### ISSUE TITLE
To what extent do Spikingformer and Spikingformer-CML differ in terms of SOP?

### ISSUE THREAD

**Issue by zachary19889** [zhouchenlin2096/Spikingformer-CML#5]
Hi, thank you for your excellent work on Spikingformer-CML. As far as I know, Spikingformer has more SOPs than Spikformer. I'm wondering if there are any differences between Spikingformer and Spikingformer-CML in SOP. If so, To what extent do Spikingformer and Spikingformer-CML differ in terms of SOP? I am eagerly awaiting your prompt response, thanks!

**Comment by zhouchenlin2096** [comment]
Both Spikingformer and Spikingformer-CML have the same SOPs.
